<?php

function scdgmap_help($path, $arg) {
  switch ($path) {
    case "admin/help#scdgmap":
      return '<p>' . t("Help text") . '</p>';
      break;
  }
} 

function scdgmap_menu() {
  $items['libraries-map'] = array(
    'title' => 'Carte des bibliothèques',
    'page callback' => 'scdgmap_libraries',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  return $items;
}

function scdgmap_libraries($pole) {
  $query = new EntityFieldQuery();
  
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'library')
    ->fieldCondition('field_lat_lon', 'value', 'NULL', '!=')
    ->fieldCondition('field_pole', 'tid', $pole)
    ->propertyCondition('status', NODE_PUBLISHED);
  
  $result = $query->execute();
  
  $nodes= array();
  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $nodes = entity_load('node', $nids);
  }

  $libraries = array();
  foreach ($nodes as $node) {
    $coords = explode(',', $node->field_lat_lon[LANGUAGE_NONE][0]['value']);

    $libraries[] = array(
      'name' => addslashes($node->title),
      'url'  => '/node/' . $node->nid,
      'lat'  => $coords[0],
      'lon'  => $coords[1],
    );
  }

  return theme('scdgmap_output', array(
    'libraries' => $libraries,
  ));
}

function scdgmap_theme($existing, $type, $theme, $path) {
  return array(
    'scdgmap_output' => array(
      'variables' => array(
        'libraries' => array(),
      ),
      'template' => 'scdgmap-output',
    ),
  );
}

?>
